// Generated by CoffeeScript 1.7.1
(function() {
  var Object, Sprite, canvas, ctx, floor_tile, getPositionFromMovement, getValidPosition, hero, keysDown, main, map, monster, monstersCaught, previous, render, renderMap, reset, spritesAreColliding, update, wall_tile,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  canvas = document.createElement('canvas');

  ctx = canvas.getContext("2d");

  canvas.width = 480;

  canvas.height = 480;

  document.body.appendChild(canvas);

  map = [[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]];

  previous = Date.now();

  Object = (function() {
    function Object(width, height, imageSource, permeable) {
      this.width = width;
      this.height = height;
      this.permeable = permeable;
      this.image = new Image();
      this.image.src = imageSource;
    }

    return Object;

  })();

  Sprite = (function() {
    function Sprite(x, y, width, height, speed, imageSource) {
      this.x = x;
      this.y = y;
      this.width = width;
      this.height = height;
      this.speed = speed;
      this.image = new Image();
      this.image.src = imageSource;
    }

    return Sprite;

  })();

  spritesAreColliding = function(spriteOne, spriteTwo) {
    if (spriteOne.x <= (spriteTwo.x + spriteTwo.width) && spriteTwo.x <= (spriteOne.x + spriteOne.width) && spriteOne.y <= (spriteTwo.y + spriteTwo.height) && spriteTwo.y <= (spriteOne.y + spriteOne.height)) {
      return true;
    } else {
      return false;
    }
  };

  floor_tile = new Object(32, 32, "images/brick.png");

  wall_tile = new Object(32, 32, "images/wall.png");

  hero = new Sprite(0, 0, 32, 32, 256, "images/hero.png");

  monster = new Sprite(0, 0, 32, 32, 256, "images/monster.png");

  monstersCaught = 0;

  keysDown = {};

  addEventListener("keydown", (function(e) {
    keysDown[e.keyCode] = true;
  }), false);

  addEventListener("keyup", (function(e) {
    delete keysDown[e.keyCode];
  }), false);

  reset = function() {
    hero.x = canvas.width / 2;
    hero.y = canvas.height / 2;
    monster.x = 32 + (Math.random() * (canvas.width - 64));
    return monster.y = 32 + (Math.random() * (canvas.height - 64));
  };

  getValidPosition = function(current, future) {
    console.log(future);
    if (map[Math.floor(future.x / 32)][Math.floor(future.y / 32)] !== 0) {
      return current;
    } else {
      return future;
    }
  };

  getPositionFromMovement = function(modifier, current_position) {
    var k, keys, position;
    keys = (function() {
      var _results;
      _results = [];
      for (k in keysDown) {
        _results.push(k);
      }
      return _results;
    })();
    position = {
      x: current_position.x,
      y: current_position.y
    };
    if ((__indexOf.call(keys, "38") >= 0)) {
      if ((hero.y - (hero.speed * modifier)) <= 0) {
        position.y = canvas.height - hero.y;
      } else {
        position.y -= hero.speed * modifier;
      }
    }
    if ((__indexOf.call(keys, "40") >= 0)) {
      if ((hero.y + (hero.speed * modifier)) >= canvas.height) {
        position.y = hero.y - canvas.height;
      } else {
        position.y += hero.speed * modifier;
      }
    }
    if ((__indexOf.call(keys, "37") >= 0)) {
      if ((hero.x - (hero.speed * modifier)) <= 0) {
        position.x = canvas.width - hero.x;
      } else {
        position.x -= hero.speed * modifier;
      }
    }
    if ((__indexOf.call(keys, "39") >= 0)) {
      if ((hero.x + (hero.speed * modifier)) >= canvas.width) {
        position.x = hero.x - canvas.width;
      } else {
        position.x += hero.speed * modifier;
      }
    }
    return position;
  };

  update = function(modifier) {
    var current_position, future_position, position;
    current_position = {
      x: hero.x,
      y: hero.y
    };
    future_position = getPositionFromMovement(modifier, current_position);
    position = getValidPosition(current_position, future_position);
    hero.x = position.x;
    hero.y = position.y;
    if (spritesAreColliding(hero, monster)) {
      monstersCaught += 1;
      return reset();
    }
  };

  renderMap = function(map) {
    var i, j, mapKey, r, v, _i, _len, _results;
    mapKey = [floor_tile, wall_tile];
    _results = [];
    for (v = _i = 0, _len = map.length; _i < _len; v = ++_i) {
      i = map[v];
      _results.push((function() {
        var _j, _len1, _results1;
        _results1 = [];
        for (r = _j = 0, _len1 = i.length; _j < _len1; r = ++_j) {
          j = i[r];
          _results1.push(ctx.drawImage(mapKey[j].image, r * mapKey[j].width, v * mapKey[j].height));
        }
        return _results1;
      })());
    }
    return _results;
  };

  render = function() {
    ctx.drawImage(hero.image, hero.x, hero.y);
    ctx.drawImage(monster.image, monster.x, monster.y);
    ctx.fillStyle = "rgb(250, 250, 250)";
    ctx.font = "24px Helvetica";
    ctx.textAlign = "left";
    ctx.textBaseline = "top";
    return ctx.fillText("Monsters caught: " + monstersCaught, 32, 32);
  };

  main = function() {
    var delta, now;
    now = Date.now();
    delta = now - previous;
    update(delta / 1000);
    renderMap(map);
    render();
    previous = now;
    return requestAnimationFrame(main);
  };

  reset();

  main();

}).call(this);
